[package]
name = "uuid_base64"
version = "0.1.3"
edition = "2021"
authors = ["Ben Santora <bensatlantik@gmail.com>"]
description = "UUID shortener"
license = "MIT"

[dependencies]
uuid = { version = "1.0", features = ["v4"] }
base64 = "0.13"
