[package]
name = "concurrency_example"
version = "0.1.2"
author = ["bensatlantik"]
edition = "2021"
description = "A simple Rust program demonstrating concurrency using threads."
license = "MIT"
keywords = ["rust", "concurrency", "threads", "example"]

