[package]
name = "concurrency_example"
version = "0.1.2"
authors = ["Ben Santora <bensatlantik@gmail.com>"]
edition = "2021"
description = "A simple Rust program demonstrating concurrency using threads."
license = "MIT"
keywords = ["rust", "concurrency", "threads", "example"]

