[package]
name = "linux_terminal_notify"
version = "0.1.0"
authors = ["Ben Santora <bensatlantik@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Rust library for sending terminal notifications on Linux systems."

[dependencies]
