[package]
name = "riscv_sim"
version = "0.1.6"
edition = "2021"
description = "A simple and efficient RISC-V instruction simulator written in Rust."
authors = ["Ben Santora <bensatlantik@gmail.com>"]
license = "MIT"

[dependencies]


